# Generated by Django 5.0.6 on 2024-05-24 19:52

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "plot_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plot_name", models.CharField(max_length=255)),
                ("plot_legend", models.JSONField()),
                ("plot_center_coordinates", models.JSONField(default=[45.735, 18.195])),
                ("plot_geojson", models.JSONField()),
                ("plot_heatmap_url", models.URLField()),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="plots", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
