# Generated by Django 5.0.6 on 2024-06-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plots", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="plot_center_coordinates",
            field=models.JSONField(default=list),
        ),
    ]
